import { WordList } from '../entities/handlers';

export const words: WordList = [
    'harsco',
    'tata',
    'taqa',
    'schiphol',
    'nrg',
    'ecn',
    'agriport',
    'nioz',
    'pwn',
    'ecomare',
    'marine',
    'noorderkwartier',
    'wadden',
    'afsluitdijk',
    'inholland',
    'laagvliegroutes',
    'noordzuidlijn',
    'aanvliegroutes',
    'randstad',
    'randstadrail',
    'ij',
    'formule',
    'race',
    'rembrandt',
    'rai',
];