module.exports = {
    'www.noordhollandsdagblad.nl': 'nhd',
    'www.leidschdagblad.nl': 'nhd',
    'www.haarlemsdagblad.nl': 'nhd',
    'www.ijmuidercourant.nl': 'nhd',
    'www.gooieneemlander.nl': 'nhd',
    'www.nhnieuws.nl' : 'nhn',
    'nos.nl': 'nos',
    'www.omroepwest.nl': 'ow',
    'www.ad.nl': 'ad',
    'www.destentor.nl': 'ds',
    'www.rtvutrecht.nl': 'rtvu',
    'www.limburger.nl': 'lim',
    'www.1limburg.nl': '1lim',
    'www.omroepflevoland.nl': 'ofl',
    'www.parool.nl': 'par',
    'www.at5.nl': 'at5',
};